package rules
import com.example.demo.model.Bill
import com.example.demo.model.BillType
import com.example.demo.model.Transaction
import com.example.demo.model.TransactionType
import com.example.demo.rules.IncreaseResponse


rule "3% decrease pt1"
	agenda-group "increase-rules"

    when
		$amount: Double()
        Bill(
        	$amount > 0.35 * base ||
        	type.equals(BillType.RSD) && balance > 330000 ||
        	!type.equals(BillType.RSD) && balance > 3300,
        	$interest: interest
        )
        $response: IncreaseResponse(valid, baseUpdate != null, interestUpdate == null)
    then
        modify($response){setInterestUpdate(0.03 * $interest);}
end

rule "3% decrease pt2"
	agenda-group "increase-rules"

    when
        Bill($main: account.balance, $bills: account.bills, $interest: interest)
        $response: IncreaseResponse(valid, baseUpdate != null, interestUpdate == null)
		accumulate(
			Bill(passedMonths() <= 12, type.equals(BillType.RSD), $transactions: transactions) from $bills and
			accumulate(
         		Transaction(type.equals(TransactionType.INCREASE), $temp: amount) from $transactions,
         		$avg: average($temp)
         	),
			$avg1: average($avg)
		)
		accumulate(
			Bill(passedMonths() <= 11, !type.equals(BillType.RSD), $transactions: transactions) from $bills and
			accumulate(
         		Transaction(type.equals(TransactionType.INCREASE), $temp: amount) from $transactions,
         		$avg: average($temp)
         	),
			$avg2: average($avg)
		)
		eval(
			$avg1.doubleValue() > 0.5 * $main || 
			$avg2.doubleValue() > 0.45 * $main
		)
    then
        modify($response){setInterestUpdate(0.03 * $interest);}
end

rule "2.5% decrease pt1"
	agenda-group "increase-rules"

    when
		$amount: Double()
        Bill(
        	$amount > 0.3 * base ||
        	type.equals(BillType.RSD) && balance > 270000 ||
        	!type.equals(BillType.RSD) && balance > 2700,
        	$interest: interest
        )
        $response: IncreaseResponse(valid, baseUpdate != null, interestUpdate == null)
    then
        modify($response){setInterestUpdate(0.025 * $interest);}
end

rule "2.5% decrease pt2"
	agenda-group "increase-rules"

    when
        Bill($main: account.balance, $bills: account.bills, $interest: interest)
        $response: IncreaseResponse(valid, baseUpdate != null, interestUpdate == null)
		accumulate(
			Bill(passedMonths() <= 11, type.equals(BillType.RSD), $transactions: transactions) from $bills and
			accumulate(
         		Transaction(type.equals(TransactionType.INCREASE), $temp: amount) from $transactions,
         		$avg: average($temp)
         	),
			$avg1: average($avg)
		)
		accumulate(
			Bill(passedMonths() <= 10, !type.equals(BillType.RSD), $transactions: transactions) from $bills and
			accumulate(
         		Transaction(type.equals(TransactionType.INCREASE), $temp: amount) from $transactions,
         		$avg: average($temp)
         	),
			$avg2: average($avg)
		)
		eval(
			$avg1.doubleValue() > 0.45 * $main || 
			$avg2.doubleValue() > 0.4 * $main
		)
    then
        modify($response){setInterestUpdate(0.025 * $interest);}
end

rule "2% decrease pt1"
	agenda-group "increase-rules"

    when
		$amount: Double()
        Bill(
        	$amount > 0.25 * base ||
        	type.equals(BillType.RSD) && balance > 220000 ||
        	!type.equals(BillType.RSD) && balance > 2200,
        	$interest: interest
        )
        $response: IncreaseResponse(valid, baseUpdate != null, interestUpdate == null)
    then
        modify($response){setInterestUpdate(0.02 * $interest);}
end

rule "2% decrease pt2"
	agenda-group "increase-rules"

    when
        Bill($main: account.balance, $bills: account.bills, $interest: interest)
        $response: IncreaseResponse(valid, baseUpdate != null, interestUpdate == null)
		accumulate(
			Bill(passedMonths() <= 10, type.equals(BillType.RSD), $transactions: transactions) from $bills and
			accumulate(
         		Transaction(type.equals(TransactionType.INCREASE), $temp: amount) from $transactions,
         		$avg: average($temp)
         	),
			$avg1: average($avg)
		)
		accumulate(
			Bill(passedMonths() <= 9, !type.equals(BillType.RSD), $transactions: transactions) from $bills and
			accumulate(
         		Transaction(type.equals(TransactionType.INCREASE), $temp: amount) from $transactions,
         		$avg: average($temp)
         	),
			$avg2: average($avg)
		)
		eval(
			$avg1.doubleValue() > 0.4 * $main || 
			$avg2.doubleValue() > 0.35 * $main
		)
    then
        modify($response){setInterestUpdate(0.02 * $interest);}
end

rule "1.5% decrease pt1"
	agenda-group "increase-rules"

    when
		$amount: Double()
        Bill(
        	$amount > 0.2 * base ||
        	type.equals(BillType.RSD) && balance > 180000 ||
        	!type.equals(BillType.RSD) && balance > 1800,
        	$interest: interest
        )
        $response: IncreaseResponse(valid, baseUpdate != null, interestUpdate == null)
    then
        modify($response){setInterestUpdate(0.015 * $interest);}
end

rule "1.5% decrease pt2"
	agenda-group "increase-rules"

    when
        Bill($main: account.balance, $bills: account.bills, $interest: interest)
        $response: IncreaseResponse(valid, baseUpdate != null, interestUpdate == null)
		accumulate(
			Bill(passedMonths() <= 9, type.equals(BillType.RSD), $transactions: transactions) from $bills and
			accumulate(
         		Transaction(type.equals(TransactionType.INCREASE), $temp: amount) from $transactions,
         		$avg: average($temp)
         	),
			$avg1: average($avg)
		)
		accumulate(
			Bill(passedMonths() <= 8, !type.equals(BillType.RSD), $transactions: transactions) from $bills and
			accumulate(
         		Transaction(type.equals(TransactionType.INCREASE), $temp: amount) from $transactions,
         		$avg: average($temp)
         	),
			$avg2: average($avg)
		)
		eval(
			$avg1.doubleValue() > 0.35 * $main || 
			$avg2.doubleValue() > 0.3 * $main
		)
    then
        modify($response){setInterestUpdate(0.015 * $interest);}
end

rule "1% decrease"
	agenda-group "increase-rules"

    when
		Bill($interest: interest)
        $response: IncreaseResponse(valid, baseUpdate != null, interestUpdate == null)
    then
        modify($response){setInterestUpdate(0.01 * $interest);}
end

