package rules
import com.example.demo.model.BillType
import com.example.demo.rules.BillRequest
import com.example.demo.rules.BillResponse


rule "NKS of 1.5%"
	agenda-group "create-rules"
	salience 5

    when
    	BillRequest(
	    	type == BillType.RSD && (months > 21 || base / months > 100000) || 
	    	type == BillType.EUR && (months > 30 || base / months > 3000) ||
	    	type == BillType.USD && (months > 27 || base / months > 2900) ||
	    	type == BillType.CHF && (months > 24 || base / months > 2800) ||
	    	type == BillType.GBP && (months > 33 || base / months > 3010)
    	)
		$response: BillResponse(valid, nks == null)
    then
    	modify($response){setNks(1.5)}
        
end

rule "NKS of 1.2%"
	agenda-group "create-rules"
	salience 4

    when
    	BillRequest(
	    	type == BillType.RSD && (months > 15 || base / months > 50000) || 
	    	type == BillType.EUR && (months > 24 || base / months > 2000) ||
	    	type == BillType.USD && (months > 21 || base / months > 1900) ||
	    	type == BillType.CHF && (months > 18 || base / months > 1800) ||
	    	type == BillType.GBP && (months > 27 || base / months > 2100)
    	)
		$response: BillResponse(valid, nks == null)
    then
    	modify($response){setNks(1.2)}
        
end

rule "NKS of 1.0%"
	agenda-group "create-rules"
	salience 3

    when
    	BillRequest(
	    	type == BillType.RSD && (months > 9 || base / months > 30000) || 
	    	type == BillType.EUR && (months > 18 || base / months > 1000) ||
	    	type == BillType.USD && (months > 15 || base / months > 900) ||
	    	type == BillType.CHF && (months > 12 || base / months > 800) ||
	    	type == BillType.GBP && (months > 21 || base / months > 1100)
    	)
		$response: BillResponse(valid, nks == null)
    then
    	modify($response){setNks(1.0)}
        
end

rule "NKS of 0.8%"
	agenda-group "create-rules"
	salience 2

    when
    	BillRequest(
	    	type == BillType.RSD && (months > 6 || base / months > 10000) || 
	    	type == BillType.EUR && (months > 12 || base / months > 500) ||
	    	type == BillType.USD && (months > 9 || base / months > 480) ||
	    	type == BillType.CHF && (months > 6 || base / months > 470) ||
	    	type == BillType.GBP && (months > 15 || base / months > 520)
    	)
		$response: BillResponse(valid, nks == null)
    then
    	modify($response){setNks(0.8)}
        
end

rule "NKS of 0.5%"
	agenda-group "create-rules"
	salience 1

    when
    	BillRequest(
	    	type == BillType.RSD && months <= 6 && base / months <= 10000 || 
	    	type == BillType.EUR && months <= 12 && base / months <= 500 ||
	    	type == BillType.USD && months <= 9 && base / months <= 480 ||
	    	type == BillType.CHF && months <= 6 && base / months <= 470 ||
	    	type == BillType.GBP && months <= 15 && base / months <= 520
    	)
		$response: BillResponse(valid, nks == null)
    then
    	modify($response){setNks(0.5)}
        
end
